version: "3.3"
services:
  jebelaw:
    image: springio/jebelaw
    build: ./
    ports:
      - 8080:8080
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    networks:
      - network1
  shemsu:
    image: node/anabeast:shemsu1
    build: ./
    ports:
      - 9090:9090
    volumes:
      - ../../shemsu:/app
  mongo:
    image: mvertes/alpine-mongo
    container_name: gimjabet
    volumes:
      - mongodb:/data/db
    ports:
      - 27017:27017
    networks:
      - network1
volumes:
  mongodb:
    
networks:
  network1:
  